name: CI

on:
  push:
    branches: 
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18.16.0'

    - name: Install dependencies
      run: npm install

    - name: Run unit tests
      run: npm test

    - name: Install Playwright
      run: npx playwright install

    - name: Run UI tests
      run: npx cucumber-js
