name: CI

on:
  push:
    branches: 
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: 18.16.0

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run unit tests
      run: npm test

    - name: Install Playwright
      run: npx playwright install

    - name: Run UI tests
      run: npx cucumber-js

